### ISSUE TITLE
Patch?

### ISSUE THREAD

**Issue by Suspect11** [target111/py-onym#4]
Hey i think they did some type of patch where 1 message per ip address can u check this out and lmk? and if its like that now can u add a proxy feature where we add proxies and can spam

**Comment by target111** [comment]
Are you sure about that? I tested it out and it seems to be the same for me. Sometimes, it does indeed get stuck, after a few hundred messages, I could add a list of proxies...

**Comment by Suspect11** [comment]
wym the same? what i said or the bot is working fine?

**Comment by target111** [comment]
Sorry, should have been more clear. I didn't notice any ip patch on their end, it works just as well as before, for me, but it does get stuck after a few hundred messages, so I will add a proxy option soon enough.

**Comment by Suspect11** [comment]
ok when u add the option lmkk reply heree

**Comment by Suspect11** [comment]
and it only sends 1 mesage not 100

**Comment by target111** [comment]
I've looked into it and it doesn't seem like there's a way to set multiple proxies with selenium, because the back-end is a browser and those are not designed for this. What I _can do_ is add an option for a single proxy and then you can use some external software like proxifier that allows you to chain.

**Comment by target111** [comment]
I have created a separate branch with a proxy option. Will only merge if more people request it, as it adds some code complexity that I don't like.
